### PR TITLE
Fix #149 unquote ragtime table name

### LINKED ISSUE #149: next-jdbc: Discover that the migration table exists even if the name is quoted
Currently if I set the migration table name to include **quoted** schema name, like this (PostgreSQL syntax): `"\"myschema\".ragtime_migrations"` then Ragtime fails to see that the table exists because it will compare this exact string (including the quotes) against the `(str table_schem "." table_name)` from the DB Metadata (which will not include quotes).

I need to have the name quoted because my schema begins with a number, which otherwise is not legal.

### PR DESCRIPTION
**Pull request by holyjak**
... before comparing it with the DB metadata - fixes #149

### CODE REVIEW

**Comment by weavejester** [comment]
Thanks for the PR, but can you explain what you're doing here? Isn't fixing #149 just a case of updating `metadata-matches-table?`?

**Comment by holyjak** [comment]
Well, yes and no. You need to talk to the DB to find out what is the quoting character so that you can ignore it in `metadata-matches-table`. And to be able to get the DB MetaData, I need a Connection - but what I actually have might be a datasource or a wrapped connection. So the new macro ensures I get a connection. (It could also be a function taking a callback that takes the connection...)

**Comment by holyjak** [comment]
To make it more concrete: at my project I have the schema `7eleven` and want the migration table there. Thus I need to give it the name quoted, i.e. - in postgres sytnax - `"\"7eleven\".ragtime_migrations"`. Currently that will cause Ragtime to never understand that the table has been created because it will be comparing `7eleven` (from metadata) against `"7eleven"` (from the configured table name).

**Comment by weavejester** [comment]
Okay, so let's remove the `with-connection`. We don't want a macro here, and certainly not a public one.

Instead, let's change `get-table-metadata` to `get-db-metadata` and have it return a map with `:quote` and `:tables`, so all the information we need is returned by one trip.

File: next-jdbc/src/ragtime/next_jdbc.clj [hunk 1]
```diff
@@ -30,8 +35,16 @@
...
-    (with-open [conn (jdbc/get-connection datasource)]
-      (get-table-metadata* conn))))
+    (with-open [c (jdbc/get-connection datasource)]
+      (get-table-metadata* c))))
+
+(defn- unquote-table-name [q table-name]
+  (if q
+    ;; Remove db quote around the schema and table name; ex.: "\"schema\".\"table\""
+    (let [pattern (re-pattern (format "^%s|%s(?=\\.)|(?<=\\.)%s|%s$"
+                                q q q q))]
```
Comment (weavejester) [inline next-jdbc/src/ragtime/next_jdbc.clj:45]: We probably want to quote `q` here, and `quote-char` would be a more descriptive name. So something more like:

```clojure
(if quote-char
  (let [re (->> (Pattern/quote quote-char)
                (format "^%1$s|%1$s(?=\\.)|(?<=\\.)%1$s|%1$s$")
                (re-pattern))]
    (str/replace table-name re ""))
  table-name)
```

File: next-jdbc/src/ragtime/next_jdbc.clj [hunk 2]
```diff
@@ -17,9 +17,14 @@
 
 ;; Returns unqualified maps as some databases (e.g. Oracle) can only return them
 (defn- get-table-metadata* [^Connection c]
-  (-> (.getMetaData c)
-      (.getTables (.getCatalog c) nil nil (into-array ["TABLE"]))
-      (rs/datafiable-result-set c {:builder-fn rs/as-unqualified-lower-maps})))
+  (let [metadata (.getMetaData c)
+         quote-str (.getIdentifierQuoteString metadata)]
```
Comment (weavejester) [inline next-jdbc/src/ragtime/next_jdbc.clj:21]: Indentation slightly off here.

File: next-jdbc/src/ragtime/next_jdbc.clj [hunk 3]
```diff
@@ -17,9 +17,14 @@
 
 ;; Returns unqualified maps as some databases (e.g. Oracle) can only return them
 (defn- get-table-metadata* [^Connection c]
```
Comment (weavejester) [inline next-jdbc/src/ragtime/next_jdbc.clj:19]: Let's call this `get-db-metadata*`.

File: next-jdbc/src/ragtime/next_jdbc.clj [hunk 4]
```diff
@@ -17,9 +17,14 @@
...
-      (.getTables (.getCatalog c) nil nil (into-array ["TABLE"]))
-      (rs/datafiable-result-set c {:builder-fn rs/as-unqualified-lower-maps})))
+  (let [metadata (.getMetaData c)
+         quote-str (.getIdentifierQuoteString metadata)]
+    {:tables
+     (-> metadata
+         (.getTables (.getCatalog c) nil nil (into-array ["TABLE"]))
+         (rs/datafiable-result-set c {:builder-fn rs/as-unqualified-lower-maps}))
+     :quote (when (not= quote-str " ")
+              quote-str)}))
```
Comment (weavejester) [inline next-jdbc/src/ragtime/next_jdbc.clj:27]: This would probably be better if we factored the two values out into functions, e.g.

```clojure
{:tables (get-table-metadata metadata)
 :quote  (get-identifier-quote metadata)}
```

File: next-jdbc/src/ragtime/next_jdbc.clj [hunk 5]
```diff
@@ -30,8 +35,16 @@
     (get-table-metadata* (:connectable datasource))
 
     :else
-    (with-open [conn (jdbc/get-connection datasource)]
-      (get-table-metadata* conn))))
+    (with-open [c (jdbc/get-connection datasource)]
+      (get-table-metadata* c))))
```
Comment (weavejester) [inline next-jdbc/src/ragtime/next_jdbc.clj:39]: Change `c` back to `conn` so that the end patch doesn't change these lines.

**Review by weavejester — CHANGES_REQUESTED** [review]

File: next-jdbc/src/ragtime/next_jdbc.clj (hunk 1 above)
Comment (holyjak) [reply next-jdbc/src/ragtime/next_jdbc.clj:45]: Wonderful idea! And thank you vermy much for teaching me about `1$`!

File: next-jdbc/src/ragtime/next_jdbc.clj [hunk 6]
```diff
@@ -11,27 +11,47 @@
...
-(defn- get-table-metadata [datasource]
+(defn- get-identifier-quote [^DatabaseMetaData metadata]
+  (let [quote-char (.getIdentifierQuoteString metadata)]
+    (when (not= quote-char " ")
+      quote-char)))
+
+(defn- get-db-metadata* [^Connection c]
+  (let [metadata (.getMetaData c)]
+    {:tables (get-table-metadata metadata c)
+     :quote (get-identifier-quote metadata)}))
```
Comment (weavejester) [inline next-jdbc/src/ragtime/next_jdbc.clj:33]: Could you align the values of the map, i.e.

```clojure
    {:tables (get-table-metadata metadata c)
     :quote  (get-identifier-quote metadata)}
```

File: next-jdbc/src/ragtime/next_jdbc.clj [hunk 7]
```diff
@@ -11,27 +11,47 @@
...
+      ;; Returns unqualified maps as some databases (e.g. Oracle) can only return them
       (rs/datafiable-result-set c {:builder-fn rs/as-unqualified-lower-maps})))
 
-(defn- get-table-metadata [datasource]
+(defn- get-identifier-quote [^DatabaseMetaData metadata]
+  (let [quote-char (.getIdentifierQuoteString metadata)]
+    (when (not= quote-char " ")
+      quote-char)))
+
+(defn- get-db-metadata* [^Connection c]
```
Comment (weavejester) [inline next-jdbc/src/ragtime/next_jdbc.clj:30]: Could you change `c` to `conn`?

File: next-jdbc/src/ragtime/next_jdbc.clj [hunk 8]
```diff
@@ -41,8 +61,10 @@
                        table_name)))
 
 (defn- table-exists? [datasource ^String table-name]
-  (some (partial metadata-matches-table? table-name)
-    (get-table-metadata datasource)))
+  (let [{:keys [tables quote]} (get-db-metadata datasource)
+        table-name-unquoted (unquote-table-name quote table-name)]
+    (some (partial metadata-matches-table? table-name-unquoted)
+      tables)))
```
Comment (weavejester) [inline next-jdbc/src/ragtime/next_jdbc.clj:67]: Could you indent this as:

```clojure
    (some (partial metadata-matches-table? table-name-unquoted)
          tables)
```

The original indent is wrong, and since these lines are being changed, it might as well be fixed here.

File: next-jdbc/src/ragtime/next_jdbc.clj [hunk 9]
```diff
@@ -41,8 +61,10 @@
                        table_name)))
 
 (defn- table-exists? [datasource ^String table-name]
-  (some (partial metadata-matches-table? table-name)
-    (get-table-metadata datasource)))
+  (let [{:keys [tables quote]} (get-db-metadata datasource)
+        table-name-unquoted (unquote-table-name quote table-name)]
```
Comment (weavejester) [inline next-jdbc/src/ragtime/next_jdbc.clj:65]: Could you align the let values, i.e.

```clojure
  (let [{:keys [tables quote]} (get-db-metadata datasource)
        table-name-unquoted    (unquote-table-name quote table-name)]
```

**Review by weavejester — CHANGES_REQUESTED** [review]
Looking good! I have a few minor formatting changes for you, but after that the patch should be fine to squash and merge.

**Comment by holyjak** [comment]
Done!

**Comment by weavejester** [comment]
Thanks. Can you squash down your changes and give it a commit message like:

    Ensure table lookup works for quoted identifiers

    Fixes #149.

**Comment by holyjak** [comment]
done

**Comment by holyjak** [comment]
Hi @weavejester ! I believe I have addressed all your comments. Please let me know if there is anything more I should do. Thank you.

**Comment by weavejester** [comment]
Apologies for the delay. I forgot about tests last time. Can you extend `test-migrations-table` with a test for this? e.g.

```clojure
(let [table "`myschema`.migrations"
        db    (jdbc/sql-database datasource {:migrations-table table})]
    (p/add-migration-id db "30")
    (is (= ["30"]
           (->> ["SELECT * FROM `myschema`.migrations"]
                (n.j/execute! (:datasource db))
                (map :MIGRATIONS/ID)))))
```

**Comment by holyjak** [comment]
Sadly I cannot. H2 returns a quote character but obviously doesn't sort quoting schema names in create table.

**Comment by weavejester** [comment]
> H2 returns a quote character but obviously doesn't sort quoting schema names in create table.

Sorry, I'm not sure I understand this. Can you explain a little further?

**Comment by holyjak** [comment]
Sorry, autcorrect on phone sucks. It should have been "support" not "sort". The H2 metadata return `"` as the quote character but anyway 

```sql
create table "myschema".migrations2 (x varchar(1))
```

fails with

```
JdbcSQLSyntaxErrorException: Schema "myschema" not found; SQL statement:
create table "myschema".migrations2 (x varchar(1)) [90079-200]
```

The schema `myschema` actually exists, but of course `"myschema"` does not. I.e. H2 does not interpret the `"` as a quote but as a literal part of the name.

**Comment by holyjak** [comment]
I have tested the patch with Postgres where it works just fine.

**Comment by holyjak** [comment]
Sorry, I found the problem. Quoted = case sensitive so I must use the schema name in upper case.

Adding the test now!

**Comment by holyjak** [comment]
I have added the test now

**Comment by holyjak** [comment]
@weavejester sorry to bother but is there anything else I should do? Thank you!

**Comment by weavejester** [comment]
Thanks - merged!
